audit_header: false
title: Houston Broker Team
description: >-
  Nuestra misión en Keller Williams es ser su mejor recurso para el
  asesoramiento inmobiliario de Houston. Si usted es un comprador, vendedor o
  inversor, nuestro equipo de profesionales puede responder cualquier pregunta
  que pueda tener sobre bienes raíces. Si está buscando comprar o vender una
  casa, puede obtener toda la información y las últimas actualizaciones,
  consejos y trucos de The Keller Williams, sus agentes inmobiliarios
  profesionales de Houston.
show_custom_links: true
custom_links:
  - title: Gemas de Houston
    url: /gemas-de-houston/
  - title: Mujeres a mujeres
    url: /mujeres-a-mujeres/
  - title: Casas destacadas
    url: /casas-destacadas/
  - title: 'Cómo comprar una casa en Houston, TX'
    url: 'https://www.amazon.com/dp/1792789300'
  - title: Desarrollo de casas adosadas
    url: /desarrollo-de-casas-adosadas/
client:
  name: Daniela Antelo
  title:
  license_number:
  about_markdown: >
    Daniela Antelo ha sido una profesional de bienes raíces con sede en Houston
    desde 2011. En el transcurso de su carrera, ha obtenido múltiples
    designaciones, como Experta en Negociación Certificada (CNE), Especialista
    Acreditado en Casas de Lujo (ALHS) y Representante de Comprador Acreditado
    (ABR) . Obtuvo su licencia de corredor en 2018 y actualmente es asociada de
    corredor con Keller Williams Realty.
  brand: Keller Williams
  brokerage: Houston Broker Team
  market: Houston
  address: '950 Corbindale Rd. Suite 100<br>Houston, TX 77024'
  phone: 713-494-8170
  phone_type:
  phone2:
  phone2_type:
  email: antelodani@gmail.com
  url: 'http://www.houstonbroker.com'
CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: 'http://web.har.com/aws/disphomeworth.cfm?siteType=aws&cid=617461'
  second_CTA_text: Home Search
  second_CTA_URL: 'http://search.har.com/idx/?siteType=aws&cid=617461'
sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: ¿Cuál es el valor de su casa en Houston?
    CTA_text: >-
      ¿Está pensando en vender su casa o está interesado en conocer los precios
      de la vivienda en su vecindario? Te podemos ayudar.
    CTA_link_text: Valor de la casa
    CTA_url: 'http://web.har.com/aws/disphomeworth.cfm?siteType=aws&cid=617461'
second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: ¿Buscando una casa en Houston?
    CTA_text2: Busca en toda la MLS tu hogar en Houston.
    CTA_link_text2: Buscar en la MLS
    CTA_url2: 'http://search.har.com/idx/?siteType=aws&cid=617461'
third_sidebar_CTA:
  - CTA_image_path3:
    CTA_title3:
    CTA_text3:
    CTA_link_text3:
    CTA_url3:
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/Houston-Broker-Dani-Antelo-2171832076399087/'
  linkedin_url:
  youtube_url: 'https://www.youtube.com/channel/UCtErXoPb-1hXn2btdLgchsQ'
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:
podcast:
  title: Houston Real Estate Podcast with Daniela Antelo
  categories:
    - Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the Houston
    Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from Keller Williams - your professional
    Houston Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in Houston, home
    selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: Daniela Antelo
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Houston Broker Team
  hero_background_hex: '#999999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#b40101'
  theme_color: '#999999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#000000'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: 'rgba(0, 0, 0, 0)'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'